# Generated by Django 4.0.4 on 2022-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(default='Форма была без описания', max_length=1000, null=True),
        ),
    ]
