# Generated by Django 4.0.4 on 2022-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(default='Надо идти на связь', max_length=1000, null=True),
        ),
    ]
